create table user_images (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  url text not null,
  alt text,
  source text default 'pexels',
  source_id text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table user_images enable row level security;

create policy "Users can view their own images"
  on user_images for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own images"
  on user_images for insert
  with check ( auth.uid() = user_id );

create policy "Users can delete their own images"
  on user_images for delete
  using ( auth.uid() = user_id );
